# -*- coding: utf-8 -*-
"""CodeAlpha_Task3_Iris_Flower_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/dharmendrayadav98/CodeAlpha_Task-3-Iris-Flower-Classification/blob/main/CodeAlpha_Task3_Iris_Flower_Classification.ipynb

## **Task 3 : Iris Flower Classification**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df =pd.read_csv('/content/Iris.csv')
df.head()

df.isnull().sum()

df.Species

"""### 1. Data Preparation


"""

df = df.drop('Id', axis=1)
X = df.drop('Species', axis=1)
y = df['Species']

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_encoded = le.fit_transform(y)

print("Original Species:", y.unique())
print("Encoded Species:", le.classes_)
print("Features (X) head:")
display(X.head())
print("Encoded Target (y) head:")
display(pd.Series(y_encoded).head())

from sklearn.model_selection import train_test_split
X = df.drop(['Species'],axis='columns')
X.head()

"""### 2. Split Data into Training and Testing Sets


"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.3, random_state=42, stratify=y_encoded)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

"""### 4. Evaluate Model Accuracy and Performance


"""

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

y_pred = knn_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")

print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=le.classes_))

conf_matrix = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(8, 6))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=le.classes_, yticklabels=le.classes_)
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

print(accuracy)

"""### Train a Logistic Regression Model


"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns


log_reg_model = LogisticRegression(max_iter=200, random_state=42)
log_reg_model.fit(X_train, y_train)

print("Logistic Regression model trained successfully!")

len(X_train)

len(X_test)